### ISSUE TITLE
Yubikey 4 error

### ISSUE THREAD

**Issue by mlegitt** [CSIS/EnrollmentStation#7]
tried using a Yubikey 4 although it read the device fine upon enrollment I receive "failed to generate key pair" error message

**Comment by ian-csis** [comment]
Hi @mlegitt,

The Yubikey 4 has never been tested with the system. Yubico has written to us to provide some tests keys such that we can get support for it. We will take a look at it as soon as we can.

**Comment by degan6** [comment]
Any update on this?
I have a yubikey 4 and am getting "unable to enroll a certificate"
I can see the light flashing on my yubikey but it don't seem to be able to write.

**Comment by mike-csis** [comment]
Does the Yubikey register with the NEO manager or PIV tool from Yubico?
We've successfully been enrolling Yubikey 4 for a while now (all 5 we had).

**Comment by degan6** [comment]
Yes, the NEO manager see's the yubikey without issue.

**Comment by degan6** [comment]
I will look into the PIV tool soon. Is their a log or any place I can look on my workstation or the server to shed some light on why it failed?

**Comment by mike-csis** [comment]
Ok. The "Unable to enroll a certificate." error comes in the process of contacting the CA to have the certificate signed. This involves the yubikey signing a request, the CA signing it and returning a certificate which is then stored on the key (in broad terms).

The error dialog should include an extended error message. I looked over the code and found an instance I believed I had covered - but the new version `0.3.3.2` covers a last case. Could you run that and see if you get more info ?

Is it just one Yubikey or multiple (or all)?

**Comment by degan6** [comment]
Unfortunately I just have one Yubikey. 
Your update did help thought. The error changed to  ![This much more helpful error.](https://cloud.githubusercontent.com/assets/7589220/15452944/4b4aebd0-1fb5-11e6-985d-5557ec9b3fa8.png)

I believe the issue is on my end now, thank you for you help.

**Comment by mike-csis** [comment]
Hi,

That's awesome. Your issue is now centered on your CA server. The specific template is not active, published, you don't have permissions .. or any other of the possible issues.

One of the cases where we receive a similarly worded error, is when the user account running the Enrollment Station isn't properly authenticated with the AD. This can happen if you at login time (in Windows) can't connect to the AD server.

In any case. You may be able to get more info on 0x80094800 on Google or by examining event logs on your CA. Lastly, the CA console has a "Failed attempts" (or similar) which might contain more info.
